name: Ament Lint

on:
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  ament_lint:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:noble
    strategy:
      fail-fast: false
      matrix:
          linter: [copyright, flake8, pep257]
    steps:
    - uses: actions/checkout@v4
    - uses: ros-tooling/setup-ros@master
    - uses: ros-tooling/action-ros-lint@master
      with:
        linter: ${{ matrix.linter }}
        package-name: ICAR2025_PHBenchmark
